engines:
  csslint:
    enabled: true
    checks:
      fallback-colors:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50
  eslint:
    enabled: true
    checks:
      complexity:
        enabled: false
  fixme:
    enabled: true

ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"

exclude_paths:
- "spec/app/**/*"
